-- definitions for Lua 5.1 package library

--# assume global `module`:
--#     var function(string, function(table)...) = "become-module"
--#
--# assume global `require`:
--#     var function(string) -> any = "require"
--#
--# assume global `package`:
--#     var {
--#         `cpath` = var string;
--#         `loaded` = var { [string] = var table };
--#         `loaders` = var { var function(string) -> (function|string|nil) };
--#         -- TODO no builtin tag for fields
--#         `loadlib` = var function(string, string);-- = "eval";
--#         `path` = var string;
--#         `preload` = var { var function(string) -> (function|string|nil) };
--#         -- TODO error type not yet supported (should it be a slot?)
--#         --`seeall` = error "package.seeall is discouraged, use _G instead";
--#     }

